returns only static content from vshosting CDN
shopsys/deployment pull request #25
Opened 2024-09-09 12:10 UTC by sspooky13

relates to https://github.com/shopsys/shopsys/pull/3419

2024-09-09 19:05 UTC, grossmannmartin requested changes

2024-09-09 19:05 UTC, grossmannmartin commented on kubernetes/configmap/nginx.yaml
> +            location ~ /$ {
Does this mean only the location ending with a slash will be filtered?

The default setting of the SSP does not use trailing slashes in URL 🤔  

Also, I have several more questions about this solution:
- the location catches all urls, but serves only @storefront location, is that ok?
- do I assume correctly, headers are automatically added by the CDN?

2024-09-20 10:59 UTC, TomasLudvik approved these changes

2024-09-20 11:53 UTC, grossmannmartin approved these changes

2024-09-20 11:53 UTC, merged